<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * A desk with a printer attached to it.
 *
 * The old agent had no such thing. It generated a fresh identifier every time
 * the page mounted, so "who printed this" was a different random string after
 * every refresh, and whether the agent was running at all was a boolean living
 * in Livewire's component state — which does not survive a reload. An office PC
 * that refreshed overnight stopped printing and nothing anywhere said so.
 *
 * A station fixes both. The browser stores its key, so the same desk rejoins as
 * itself after a reload, a crash or a reboot; the row records what that desk can
 * do and when it was last heard from, so a manager in another branch can see
 * that the Bole desk has been silent since Tuesday without walking over to it.
 *
 * Liveness is a heartbeat rather than a flag. A flag says what somebody once
 * intended; last_seen_at says what is true now, which is the question being
 * asked when a report did not come out.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('print_stations', function (Blueprint $table) {
            $table->id();

            // Generated by the browser on first use and kept in localStorage.
            // Not guessable, because knowing one would let another tab claim
            // this desk's jobs and print member data somewhere else.
            $table->string('key', 64)->unique();

            $table->string('name');
            $table->string('location')->nullable();

            // The station's own switch, independent of the master switch. A
            // branch closing for Ramadan turns off its own desk without
            // affecting head office.
            $table->boolean('is_enabled')->default(true);

            // What this desk prints on. A thermal roll cannot render an A4
            // layout, so the station — not the schedule — has the last word on
            // paper, because the schedule does not know which desk will take it.
            $table->string('paper')->default('a4');
            $table->unsignedTinyInteger('max_copies')->default(5);

            // Free text for the operator: "HP 1102 in the back office, tray 2".
            // The browser will not tell us which printer it is set to default
            // to, so the note is the only record of what the paper comes out of.
            $table->string('printer_hint')->nullable();

            // Silent printing, measured rather than assumed.
            //
            // Chrome and Edge print without a dialog only when launched with
            // --kiosk-printing. Nothing in the DOM exposes that flag, so it is
            // detected from behaviour: window.print() blocks while a dialog is
            // open and returns in a few milliseconds when there is none. The
            // measurement is stored so the page can state the position plainly
            // instead of printing a setup tip and hoping.
            $table->boolean('silent_ready')->default(false);
            $table->unsignedInteger('silent_probe_ms')->nullable();
            $table->timestamp('silent_checked_at')->nullable();

            // Liveness.
            $table->timestamp('last_seen_at')->nullable();
            $table->timestamp('listening_since')->nullable();
            $table->string('browser', 120)->nullable();
            $table->string('platform', 60)->nullable();

            // Running totals. Kept here so the page can show a desk's history
            // without scanning the jobs table once per station on every poll.
            $table->unsignedInteger('printed_count')->default(0);
            $table->unsignedInteger('failed_count')->default(0);
            $table->timestamp('last_printed_at')->nullable();
            $table->string('last_error', 500)->nullable();
            $table->timestamp('last_error_at')->nullable();

            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();

            // The agent's poll asks "which enabled stations are alive", which
            // is exactly this index.
            $table->index(['is_enabled', 'last_seen_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('print_stations');
    }
};
